before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
  - docker version
  - export

env:
  global:
  - DOCKER_BUILDKIT=1
  - secure: 2mE1D8TuP9TZzStVvAPgtniI4oaNqb8ZszI+TSIHidGtSdzSEp9jyaUh1RVVcNbc9XVnutmV0BiDbxVkE5s86GPP+MjZl3stbA0IYK2uf9p9z71qg/u7kVlGOfvpaOvwHRc4N46pDtyqDLMb9tMQAOLLoiWOdPAdj6YG4kL+qvoobDRdokzpYw6E+HRRu2MD3z1bKrFM8DTOnZYcT/H02XWa59k+qR3y9TGN2k8wEgZ1lOV/3IbqskjPh2y4OZhWPSPsE2CcG+APpv4ROQ+dWoAjsmpmPDu7CV62qmCAe1JM0mTrjgPr/9n2NGFbmIW+h7bxdP1X/i3ysrpmcczI9PXz4UQ0Zt41DSIMn/EsmO6amccaIkEWQYliyjtD+iZ4MdKFWPDyE8baGOqWRGLP+DINf9bU35tI5u9FU1oTixE7s+bJcPGueRx7465zQVO+id5Ei7xSYCGT8i1MjBRFcxyeduoqMD+AKNLAl8Px76Y5+KjXLd4qrkQjx8wsOJ1DAz1d/uf5zLouuWAKCz7ORi5sDUjaQ6O/5qffp4EYitXsKFXSAvJXcx+KcVVCV/TWNZ6PyYuN7RJCBNfH7+YUPtUhhfjWmD/baoTKPUkAywM4iGp6FlJOzhy9Yncje5H/oEbqP+j9g/3h9EZWdzupkRMm1Ae/BgTCLoOEzks2A58=

services:
  - docker

script:
  - make build
  - docker run --detach --name openvpn-monitor --publish 8080:80 samuelkadolph/openvpn-monitor
  - sleep 3
  - curl http://localhost:8080 | grep "Example OpenVPN Status Monitor"
  - docker kill openvpn-monitor
