env:
  global:
    secure: NYmeV4E5xHBfMomqSaxSKvMw91zlw7R/FgB1zIVWRntzyUWZVhYEo2MhoZygzHt7IroyzlS3WElOv2VSL9ONrbTeashix1KrkngxnQJnHEKUPO+rIyFBEMlSm2nFvzqmy4bkLkXimz4q4agyd/mPKNQHYy6QqUqNCtBrNayEMnOoNpmJEukHxDprSSeL2jUxOJog+W1rmCj6bgtzQF+AMXbvQ3Ukcd0oLzOLLhjUNS2FZWbLD4JrwgXU+9SZgOuj7a+AK1iMpH5rYJ01JhRSZ4vp4N200pC6YR2i1HXXqONXPp+QK32X1LvhEm29x7skqlP7FtM+KIgANV9unqtplRWimnrUxN9xyChqM7ph9g5IzfNswdv5oa34Fhpa+xOaHpp619F9lPsBz/tiFdANrvJAN9/SXWPfr52gkgJnpY/jwEBICSPQy0gGlUgRxs/zcRgOH3uXJ15vbGPdghGfFJujI85Z57Kv5f6GWR37+RYYUhcreAnWIgwFT70L6e9oIpuQVj9nc+q0qf6z8/l9nXWs4+vti4xK3VSPxDjbbgjOrJeiwIhBJiZabo6cmdWmQxabmw5Vpuub2KOqDkWvJJDe/O1MViVmPuadZuHq/da8gyRRYtHh/yDaUmUoskQJNn006HEMN3b1KjAEWkugoCld2z3j3vSYh+tVHdYqT1o=

services:
  - docker

script:
  - make build
  - docker run --detach --name openvpn-monitor --publish 8080:80 samuelkadolph/openvpn-monitor
  - sleep 3
  - curl http://localhost:8080 | grep "Example OpenVPN Status Monitor"
  - docker kill openvpn-monitor
